#!/bin/bash -ex
# we should always set proper ownership before exiting, otherwise
# the created packages will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'chown -R --reference /build-inside/build-package /out/' EXIT

# the source directory is mounted read-only to prevent issues where the build
# could alter the source; we should copy it somewhere inside the container
cd /tmp
rsync -a /source .
cd source
mkdir buildrelease && cd buildrelease
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DHAVE_RULES=ON -DUSE_BUNDLED_TINYXML2=ON ..
make -j8
make install

cd /out
# this is a standard fpm command. look at fpm's own help. The only thing that I like to do
# is installing all the things in a separate dir to prevent listing all the files - but it's
# just personal taste.
# remember to list all your runtime dependencies, e.g. the shared libraries you link to.
fpm -t deb -s dir --name cppcheck --version ${VERSION} --description "my version of cppcheck" \
    --depends libc6 --depends libgcc1 --depends libpcre3 --depends libstdc++6 \
    --config-files /usr/local/share/Cppcheck \
    -C / /usr/local/bin/cppcheck /usr/local/share/Cppcheck
